### ISSUE TITLE
Consider blacklisting Cypress Bootloader Service

### ISSUE THREAD

**Issue by beaufortfrancois** [WebBluetoothCG/registries#11]
The Cypress Bootloader Service allows a Bootloader component to update the existing firmware on the Cypress BLE device using the Bluetooth Low Energy interface as a communication interface.
Source: http://www.cypress.com/documentation/application-notes/an97060-psoc-4-ble-and-proc-ble-over-air-ota-device-firmware-upgrade

GATT Service UUID: `00060000-0000-1000-8000-00805F9B34FB`

**Comment by jyasskin** [comment]
Where did you get the UUID from? I don't see it in either of the downloads from your link. Is there any more documentation than the Guide there, which might say something about signing or a physical enabling button?

It's frustrating that they've allocated themselves a 32-bit UUID without any assignment I can find on https://www.bluetooth.com/specifications/assigned-numbers, but we do need to blacklist it if the full implementation doesn't check signatures.

**Comment by beaufortfrancois** [comment]
I got the UUID from [CYPRESS BOOTLOADER SERVICE_001-97547.pdf](http://www.cypress.com/file/175561/download) (account required) linked in http://www.cypress.com/documentation/software-and-drivers/cypresss-custom-ble-profiles-and-services
