### ISSUE TITLE
Add Serial Number String Characteristic to blacklisted items 

### ISSUE THREAD

**Issue by beaufortfrancois** [WebBluetoothCG/registries#2]
https://developer.bluetooth.org/gatt/characteristics/Pages/CharacteristicViewer.aspx?u=org.bluetooth.characteristic.serial_number_string.xml 

See https://code.google.com/p/chromium/issues/detail?id=532930 for background.

**Comment by TaTiSh777** [comment]
setup

**Comment by TaTiSh777** [comment]
: Blacklist the Serial Number String.

**Comment by TaTiSh777** [comment]
open https://vk.com/id133908874

**Comment by ariccio** [comment]
Does this really comport with the policy that is "Blocklisting UUIDs used on only vulnerable devices is preferred"? I'm trying to read the serial number of a device that actually does have unique serial numbers per device, and I'm running into this...
