### ISSUE TITLE
Blacklist the TI Over-the-Air Download service

### ISSUE THREAD

**Issue by jyasskin** [WebBluetoothCG/registries#8]
Like the Nordic DFU service (#7), TI's update service also doesn't require signatures by default. The CC254x version of it appears to have support for encrypting the image with a symmetric key that would be embedded in all copies of the firmware, but that's missing from the CC26xx version.

This UUID is `f000ffc0-0451-4000-b000-000000000000`.

**Comment by beaufortfrancois** [comment]
Please, can you share some documentation links?

**Comment by jyasskin** [comment]
You have to install the BLE SDK from http://www.ti.com/tool/ble-stack to get most of the documentation, including the UUID. There's a video on that page that describes the OAD feature at a high level, and http://www.ti.com/lit/ug/swru271g/swru271g.pdf mentions the possibility of symmetric encryption.

**Comment by beaufortfrancois** [comment]
Thank you @jyasskin!

For future reference, 

> Version 1.3 Dec 12, 2012
> ...
> A new Over-the-air firmware download (OAD) feature is included. The feature allows a peer device
> (which could be a central BT Smart device such as a smartphone) to push a new firmware image onto a peripheral device and update the firmware. This feature uses the BIM, in which case the downloaded image gets stored in the opposite flash location as the currently running image. For example, if the "A" image is the current image and is used to perform the download, then the downloaded image becomes the "B" image. Upon reset, the "B" image with the updated firmware would be loaded. **The OAD feature optionally allows for the firmware image to be signed (using AES)**. Both the SensorTag and SimpleBLEPeripheral projects include configurations for using the OAD feature. A central "OADManager" application is also included, demonstrating a central implementation for sending a new
> firmware image to an OAD target device.
